### PR TITLE
Feature: Configuration file

### PR DESCRIPTION
**Pull request by Tony763**
Hi, take this as first draft for now.

- added example.config.json
- args and conf are used - for now (config has higher priority
- added check if given files paths are relative or absolute and handle them
- added check if at least one feed url is given
- addeditems-******.txt is generated per config name(path)

Any comment welcome.

### CODE REVIEW

**Comment by lupus78** [comment]
I like it.

Why not define boolean as boolean in the config.json? 
`"add-paused" : true,`
would not translate to Python True?

Can you update the requirements.txt with the new packages?

**Comment by Tony763** [comment]
Regarding booleans,  I read some forum posts and there was always some hacking to do that.   I will try to play with that a little more.
Added packages are already included in python installation. I have python 3.7.7

**Comment by Tony763** [comment]
This should be better.

**Comment by Tony763** [comment]
Also updated example config.
Before merge I will rebase it to one commit.

**Pull request closed without merging**
