### PR TITLE
Feature: search-patterns-list

### PR DESCRIPTION
**Pull request by Tony763**
Added function with paterns stored in text file
It is more convient that you don't have to edit you chron job and instead you can change your paterns on the fly.

Added paterns.txt to .gitignore
Added info to README.md an removed text about https as it is solved with new transmission rpc client.

### CODE REVIEW

**Comment by lupus78** [comment]
2 notes:

1. Can you follow my function naming convention? Please rename `def searchpatern(title, searchitems)` to `searchPattern`

2. Because the app is designed to run multiple times (in case you want to monitor more than one feed), I would rather see this functionality to be based on a file provided in the command line:  --search-patterns-list <filepath> so one can specify the patterns for each run.

Can you make these changes?

**Comment by Tony763** [comment]
No problem :)
Just rewot, but I can test in in evening.

**Comment by Tony763** [comment]
Tested.

**Comment by lupus78** [comment]
Pls update the Readme.md

**Comment by Tony763** [comment]
Should be already updated, line 46-48. Or may I add more details?

**Comment by lupus78** [comment]
It all ok, sorry, I skipped it

**Comment by Tony763** [comment]
No problem.  Hacktoberfest accepted? pls.

Also I think about config file, so we do not need to set all transmission credentials in arguments. What do You think?

**Comment by lupus78** [comment]
I had to push a fix for the case when the pattern file was not specified.

The config file is a good idea. Propose a clean format.

**Comment by Tony763** [comment]
Sorry for typo with pattern I send a PR with all 3 cases tested.

For config file, I think about Json file as it would be easy to program and use. Transmission use it also so it would not be problem for users. Also is necessary to hash password or not?

**Comment by lupus78** [comment]
ok, make a PR.

**Pull request merged**
