### PR TITLE
Fix error when no pattern file is defined

### PR DESCRIPTION
**Pull request by Tony763**
Sry I forget to test it
Tested:
Nothing defined
Search pattern defined
Search patterns file is defined
If both are defined search_patterns_file is used

### CODE REVIEW

**Comment by lupus78** [comment]
I have already fix this in the master branch

**Comment by Tony763** [comment]
Yes, but with this line 97  `if searchitems is None or` you will also skip `args.search_pattern` as it is checked inside  `def searchPattern`

**Comment by lupus78** [comment]
I see what you say.... but if you make that json config, than we can get rid of the search pattern way of inputting patterns, so it won't be an issue... so stay like this and let's fix it with the config file.

**Comment by Tony763** [comment]
I though about leaving booth possibilities so user can chose if use config or arguments way.

**Comment by lupus78** [comment]
That would just make the code way too complex. Either the arguments or the config file.
Come up with a config file format and create a example.config.json file
Have an argument to specify the config file.
The important part is to have validation for the config file, and if any value is missing than fill in with the defaults.
Probably a good idea to have the "addeditems.txt" for each config file.

**Comment by Tony763** [comment]
I though about adding just these to config and if some of them miss then add them from args if set an if not then load them from defaults.
```
{
    "transmission-host" : "localhost",
    "transmission-port" : "9091",
    "transmission-user" : "",
    "transmission-password" : "",
    "log-file" : "",
    "add-paused" : "",
    "download-dir" : "",
    "download-with-python" : ""
}
```

Or you want to get rid of all args and use few configs with separate logs and addeditems?

**Pull request closed without merging**
